// <auto-generated />
namespace MovieReview_WebForm_Proj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deletedMovieNameFromMovieDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletedMovieNameFromMovieDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201702031703561_deletedMovieNameFromMovieDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
